(cl:defpackage crops_wp6_arm_msgs-msg
  (:use )
  (:export
   "<JOINTMOVEMENTGOAL>"
   "JOINTMOVEMENTGOAL"
   "<JOINTMOVEMENTACTIONRESULT>"
   "JOINTMOVEMENTACTIONRESULT"
   "<JOINTMOVEMENTACTION>"
   "JOINTMOVEMENTACTION"
   "<JOINTMOVEMENTACTIONGOAL>"
   "JOINTMOVEMENTACTIONGOAL"
   "<JOINTMOVEMENTACTIONFEEDBACK>"
   "JOINTMOVEMENTACTIONFEEDBACK"
   "<JOINTMOVEMENTRESULT>"
   "JOINTMOVEMENTRESULT"
   "<JOINTMOVEMENTFEEDBACK>"
   "JOINTMOVEMENTFEEDBACK"
  ))

