; Auto-generated. Do not edit!


(cl:in-package crops_wp6_arm_msgs-msg)


;//! \htmlinclude JointMovementGoal.msg.html

(cl:defclass <JointMovementGoal> (roslisp-msg-protocol:ros-message)
  ((jointGoal
    :reader jointGoal
    :initarg :jointGoal
    :type sensor_msgs-msg:JointState
    :initform (cl:make-instance 'sensor_msgs-msg:JointState)))
)

(cl:defclass JointMovementGoal (<JointMovementGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <JointMovementGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'JointMovementGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name crops_wp6_arm_msgs-msg:<JointMovementGoal> is deprecated: use crops_wp6_arm_msgs-msg:JointMovementGoal instead.")))

(cl:ensure-generic-function 'jointGoal-val :lambda-list '(m))
(cl:defmethod jointGoal-val ((m <JointMovementGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader crops_wp6_arm_msgs-msg:jointGoal-val is deprecated.  Use crops_wp6_arm_msgs-msg:jointGoal instead.")
  (jointGoal m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <JointMovementGoal>) ostream)
  "Serializes a message object of type '<JointMovementGoal>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'jointGoal) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <JointMovementGoal>) istream)
  "Deserializes a message object of type '<JointMovementGoal>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'jointGoal) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<JointMovementGoal>)))
  "Returns string type for a message object of type '<JointMovementGoal>"
  "crops_wp6_arm_msgs/JointMovementGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'JointMovementGoal)))
  "Returns string type for a message object of type 'JointMovementGoal"
  "crops_wp6_arm_msgs/JointMovementGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<JointMovementGoal>)))
  "Returns md5sum for a message object of type '<JointMovementGoal>"
  "03f8456b346613dcdf3d0e35b6b1a281")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'JointMovementGoal)))
  "Returns md5sum for a message object of type 'JointMovementGoal"
  "03f8456b346613dcdf3d0e35b6b1a281")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<JointMovementGoal>)))
  "Returns full string definition for message of type '<JointMovementGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal definition~%sensor_msgs/JointState jointGoal~%~%================================================================================~%MSG: sensor_msgs/JointState~%# This is a message that holds data to describe the state of a set of torque controlled joints. ~%#~%# The state of each joint (revolute or prismatic) is defined by:~%#  * the position of the joint (rad or m),~%#  * the velocity of the joint (rad/s or m/s) and ~%#  * the effort that is applied in the joint (Nm or N).~%#~%# Each joint is uniquely identified by its name~%# The header specifies the time at which the joint states were recorded. All the joint states~%# in one message have to be recorded at the same time.~%#~%# This message consists of a multiple arrays, one for each part of the joint state. ~%# The goal is to make each of the fields optional. When e.g. your joints have no~%# effort associated with them, you can leave the effort array empty. ~%#~%# All arrays in this message should have the same size, or be empty.~%# This is the only way to uniquely associate the joint name with the correct~%# states.~%~%~%Header header~%~%string[] name~%float64[] position~%float64[] velocity~%float64[] effort~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.secs: seconds (stamp_secs) since epoch~%# * stamp.nsecs: nanoseconds since stamp_secs~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%# 0: no frame~%# 1: global frame~%string frame_id~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'JointMovementGoal)))
  "Returns full string definition for message of type 'JointMovementGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal definition~%sensor_msgs/JointState jointGoal~%~%================================================================================~%MSG: sensor_msgs/JointState~%# This is a message that holds data to describe the state of a set of torque controlled joints. ~%#~%# The state of each joint (revolute or prismatic) is defined by:~%#  * the position of the joint (rad or m),~%#  * the velocity of the joint (rad/s or m/s) and ~%#  * the effort that is applied in the joint (Nm or N).~%#~%# Each joint is uniquely identified by its name~%# The header specifies the time at which the joint states were recorded. All the joint states~%# in one message have to be recorded at the same time.~%#~%# This message consists of a multiple arrays, one for each part of the joint state. ~%# The goal is to make each of the fields optional. When e.g. your joints have no~%# effort associated with them, you can leave the effort array empty. ~%#~%# All arrays in this message should have the same size, or be empty.~%# This is the only way to uniquely associate the joint name with the correct~%# states.~%~%~%Header header~%~%string[] name~%float64[] position~%float64[] velocity~%float64[] effort~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.secs: seconds (stamp_secs) since epoch~%# * stamp.nsecs: nanoseconds since stamp_secs~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%# 0: no frame~%# 1: global frame~%string frame_id~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <JointMovementGoal>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'jointGoal))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <JointMovementGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'JointMovementGoal
    (cl:cons ':jointGoal (jointGoal msg))
))
