; Auto-generated. Do not edit!


(cl:in-package crops_wp6_arm_msgs-msg)


;//! \htmlinclude JointMovementResult.msg.html

(cl:defclass <JointMovementResult> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass JointMovementResult (<JointMovementResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <JointMovementResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'JointMovementResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name crops_wp6_arm_msgs-msg:<JointMovementResult> is deprecated: use crops_wp6_arm_msgs-msg:JointMovementResult instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <JointMovementResult>) ostream)
  "Serializes a message object of type '<JointMovementResult>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <JointMovementResult>) istream)
  "Deserializes a message object of type '<JointMovementResult>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<JointMovementResult>)))
  "Returns string type for a message object of type '<JointMovementResult>"
  "crops_wp6_arm_msgs/JointMovementResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'JointMovementResult)))
  "Returns string type for a message object of type 'JointMovementResult"
  "crops_wp6_arm_msgs/JointMovementResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<JointMovementResult>)))
  "Returns md5sum for a message object of type '<JointMovementResult>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'JointMovementResult)))
  "Returns md5sum for a message object of type 'JointMovementResult"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<JointMovementResult>)))
  "Returns full string definition for message of type '<JointMovementResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'JointMovementResult)))
  "Returns full string definition for message of type 'JointMovementResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <JointMovementResult>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <JointMovementResult>))
  "Converts a ROS message object to a list"
  (cl:list 'JointMovementResult
))
