/* Auto-generated by genmsg_cpp for file /home/tienthanh/workspace/ros/fuerte/mebios/tienthanh/crops_wp6_manipulator/crops_wp6_arm_msgs/msg/JointMovementFeedback.msg */
#ifndef CROPS_WP6_ARM_MSGS_MESSAGE_JOINTMOVEMENTFEEDBACK_H
#define CROPS_WP6_ARM_MSGS_MESSAGE_JOINTMOVEMENTFEEDBACK_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace crops_wp6_arm_msgs
{
template <class ContainerAllocator>
struct JointMovementFeedback_ {
  typedef JointMovementFeedback_<ContainerAllocator> Type;

  JointMovementFeedback_()
  {
  }

  JointMovementFeedback_(const ContainerAllocator& _alloc)
  {
  }


  typedef boost::shared_ptr< ::crops_wp6_arm_msgs::JointMovementFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::crops_wp6_arm_msgs::JointMovementFeedback_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct JointMovementFeedback
typedef  ::crops_wp6_arm_msgs::JointMovementFeedback_<std::allocator<void> > JointMovementFeedback;

typedef boost::shared_ptr< ::crops_wp6_arm_msgs::JointMovementFeedback> JointMovementFeedbackPtr;
typedef boost::shared_ptr< ::crops_wp6_arm_msgs::JointMovementFeedback const> JointMovementFeedbackConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::crops_wp6_arm_msgs::JointMovementFeedback_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::crops_wp6_arm_msgs::JointMovementFeedback_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace crops_wp6_arm_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::crops_wp6_arm_msgs::JointMovementFeedback_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::crops_wp6_arm_msgs::JointMovementFeedback_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::crops_wp6_arm_msgs::JointMovementFeedback_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const  ::crops_wp6_arm_msgs::JointMovementFeedback_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::crops_wp6_arm_msgs::JointMovementFeedback_<ContainerAllocator> > {
  static const char* value() 
  {
    return "crops_wp6_arm_msgs/JointMovementFeedback";
  }

  static const char* value(const  ::crops_wp6_arm_msgs::JointMovementFeedback_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::crops_wp6_arm_msgs::JointMovementFeedback_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
\n\
\n\
";
  }

  static const char* value(const  ::crops_wp6_arm_msgs::JointMovementFeedback_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::crops_wp6_arm_msgs::JointMovementFeedback_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::crops_wp6_arm_msgs::JointMovementFeedback_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct JointMovementFeedback_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::crops_wp6_arm_msgs::JointMovementFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::crops_wp6_arm_msgs::JointMovementFeedback_<ContainerAllocator> & v) 
  {
  }
};


} // namespace message_operations
} // namespace ros

#endif // CROPS_WP6_ARM_MSGS_MESSAGE_JOINTMOVEMENTFEEDBACK_H

